---
- name: add oracle java repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java'
  tags: [ 'java' ]

- name: Autoaccept license for Java8
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  tags: [ 'java' ]

- name: install oracle jdk
  become: yes
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default
  tags: [ 'java' ]
