---
- name: create partition
  become: yes
  partition: dev=/dev/sdc
  tags: [ 'hdd' ]

- name: format disk
  become: yes
  filesystem: fstype=ext4 dev=/dev/sdc1 opts='-L workspace'
  tags: [ 'hdd' ]

- name: create mount point
  file: path={{ home_dir }}/workspace state=directory
  tags: [ 'hdd' ]

- name: mount partition
  become: yes
  mount:
    name: "{{ home_dir }}/workspace"
    src: LABEL=workspace
    fstype: ext4
    state: mounted
  tags: [ 'hdd' ]

- name: change permission
  become: yes
  file: path={{ home_dir }}/workspace state=directory owner=ubuntu group=ubuntu
  tags: [ 'hdd' ]
